### ISSUE TITLE
publish master to npm?

### ISSUE THREAD

**Issue by tjmehta** [thenables/timeout-then#9]
All changes after v1.0.0 are missing on npm

**Comment by haoxins** [comment]
😢   ping @jonathanong 

https://github.com/thenables/timeout-then/pull/8

**Comment by jonathanong** [comment]
ran `npm owner add coderhaoxin timeout-then` :)

**Comment by haoxins** [comment]
85dbe8271f33bd6bd824f31d4e6f1117278e07e8

`v1.1.0`

**Comment by tjmehta** [comment]
Thanks!
